"""Individually authored, read-only Watcher algorithm modules."""
from __future__ import annotations

from importlib import import_module
from collections.abc import Sequence
from functools import lru_cache
from typing import Any, Mapping

from ._common import CachedState

ALGORITHM_MODULES = (
    "trend_continuation",
    "trend_pullback",
    "range_edge_fade",
    "failed_breakout",
    "breakout_continuation",
    "volume_effort_result",
    "pyramiding",
    "adverse_selection",
    "time_stop",
    "intermarket_analysis",
    "noise_filter",
    "tail_risk",
    "event_arbitrage",
    "spread_scalping",
    "latency_arbitrage",
    "rebate_capture",
    "market_impact_symmetry",
    "dejong_roll_spread_estimator",
    "dejong_spread_decomposition",
    "dejong_duration_weighted_spread",
    "al_brooks_high_low_count",
    "al_brooks_wedge",
    "al_brooks_failed_failure",
    "al_brooks_spike_channel",
    "al_brooks_double_flag",
    "al_brooks_range_location",
    "volman_double_doji_break",
    "volman_first_break",
    "volman_second_break",
    "volman_block_break",
    "volman_range_break",
    "volman_inside_range_break",
    "volman_advanced_range_break",
    "volman_tipping_point_exit",
    "volman_unfavorable_path_filter",
    "volman_pullback_quality",
    "vpa_long_legged_doji",
    "vpa_narrow_spread_high_volume",
    "vpa_stopping_volume",
    "vpa_topping_out_volume",
    "vpa_breakout_volume_validation",
    "vpa_trend_effort_confirmation",
    "edwards_magee_head_shoulders",
    "edwards_magee_triangle_breakout",
    "edwards_magee_gap_classification",
    "edwards_magee_support_resistance_flip",
    "edwards_magee_channel_deterioration",
    "edwards_magee_one_day_reversal",
    "edwards_magee_selling_climax",
    "edwards_magee_trendline_penetration",
    "edwards_magee_broadening_breakout",
    "edwards_magee_key_reversal_day",
    "edwards_magee_spike_reversal",
    "edwards_magee_runaway_day",
    "edwards_magee_dow_confirmation",
    "edwards_magee_basing_points_stop",
    "edwards_magee_breakout_confirmation",
    "edwards_magee_climactic_volume_stop",
    "edwards_magee_defensive_exit",
    "ponsi_level_bounce",
    "ponsi_intraday_breakout",
    "ponsi_pennant_continuation",
    "ponsi_round_number_bounce",
    "ponsi_boomerang_fade",
    "anderson_high_volume_runner",
    "nison_three_line_break",
    "nison_renko_trend",
    "nison_kagi_yang_yin",
    "nison_disparity_reversal",
    "nison_hammer_hanging_man",
    "nison_shooting_star",
    "nison_doji_confirmation",
    "nison_two_line_reversal",
    "nison_three_line_star",
    "nison_spring_upthrust",
    "nison_last_engulfing",
    "nison_window_context",
    "nison_record_sessions",
    "nison_harami",
    "nison_harami_cross",
    "nison_two_black_gapping",
    "nison_three_windows",
    "nison_gapping_doji",
    "nison_extra_line_break_confirmation",
    "nison_three_line_neck",
    "nison_kagi_double_window",
    "nison_kagi_tweezers",
    "nison_kagi_three_buddha",
    "aldridge_order_flow_autocorrelation",
    "aldridge_trade_aggressiveness",
    "aldridge_bid_ask_bounce_filter",
    "aldridge_quote_duration",
    "aldridge_trade_direction_uncertainty",
    "aldridge_quote_matching",
    "aldridge_triangular_arbitrage",
    "aldridge_uip_arbitrage",
    "aldridge_index_composition_arbitrage",
    "aldridge_volatility_curve_arbitrage",
    "aldridge_futures_basis_arbitrage",
    "aldridge_futures_etf_arbitrage",
    "aldridge_dual_class_arbitrage",
    "aldridge_risk_arbitrage",
    "aronson_objective_rule_definition",
    "aronson_reality_check",
    "aronson_practical_significance",
    "aronson_detrended_rule_return",
    "johnson_implementation_shortfall",
    "johnson_adaptive_shortfall",
    "johnson_price_inline",
    "johnson_liquidity_seeking",
    "johnson_order_difficulty",
    "elliott_impulse_rules",
    "elliott_corrective_structure",
    "elliott_alternation",
    "price_in_time_ntz_projection",
    "price_in_time_range_cycle",
    "price_in_time_pending_order",
    "price_in_time_ntz_breakout",
    "price_in_time_trade_management_models",
    "price_in_time_opening_price",
    "price_in_time_session_filter",
    "price_in_time_anomaly_filter",
    "thomas_push_pull_10xroi",
    "thomas_ma_momentum_filter",
    "thomas_break_even_after_pullback",
    "thomas_fixed_r_target",
    "thomas_breakout_context",
    "thomas_parabolic_exhaustion_exit",
    "tharp_narrow_range_breakout",
    "tharp_failed_test_reversal",
    "tharp_mae_winner_band",
    "tharp_r_multiple_expectancy",
    "tharp_market_selection",
    "ponsi_ema_trend_technique",
    "ponsi_squeeze_play",
    "ponsi_multitimeframe_pullback",
    "ponsi_fibonacci_trend_reentry",
    "ponsi_price_action_level",
    "ponsi_round_trip",
    "ponsi_interest_rate_edge",
    "clenow_dual_ema_breakout",
    "clenow_regime_filter",
    "clenow_atr_impact_sizing",
    "clenow_currency_exposure",
    "clenow_countertrend_pullback",
    "clenow_term_structure_carry",
    "clenow_core_breakout",
    "clenow_core_exit",
    "clenow_volatility_trailing_stop",
    "clenow_style_diversification",
    "silvani_retail_contrarian",
    "silvani_rolling_pivot_filter",
    "silvani_friday_stop_run",
    "aziz_abcd_pattern",
    "aziz_bull_flag_momentum",
    "aziz_red_to_green",
    "aziz_bhod",
    "grail_time_anchor_breakout",
    "chan_linear_mean_reversion",
    "chan_kalman_mean_reversion",
    "chan_cross_sectional_mean_reversion",
    "chan_time_series_momentum",
    "chan_alexander_filter",
    "chan_opening_gap_momentum",
    "chan_news_drift",
    "chan_stop_order_momentum",
    "chan_order_flow_momentum",
    "chan_bid_ask_imbalance",
    "chan_ratio_trade",
    "chan_ticking_quote_matching",
    "chan_hft_quote_data_requirements",
    "chan_bulk_volume_order_flow",
    "chan_leveraged_rebalance_momentum",
    "chan_half_kelly_cap",
    "chan_adf_mean_reversion",
    "chan_hurst_stationarity",
    "chan_variance_ratio_stationarity",
    "chan_mean_reversion_half_life",
    "chan_cadf_cointegration",
    "chan_johansen_cointegration",
    "ultimate_price_rejection",
    "ultimate_ema_reversal",
    "ultimate_head_shoulders",
    "ultimate_double_triple_test",
    "ultimate_vpa_extreme",
    "ultimate_mtf_confirmation",
    "ultimate_mw_bat_pattern",
    "ultimate_correlation_lag",
    "ultimate_abandoned_baby_ema5",
    "ultimate_triangle_pattern",
    "ultimate_cascade_exhaustion",
    "ultimate_sandwich_pattern",
    "ultimate_fractal_pattern",
    "ultimate_local_extrema_timing",
    "ultimate_sentiment_change",
    "ultimate_high_performance_confluence",
    "ultimate_news_sr_reaction",
    "pf_three_box_catapult",
    "pf_double_top_bottom",
    "pf_triple_top_bottom",
    "pf_pole_reversal",
    "pf_trendline_signal_confirmation",
    "pf_opposing_poles",
    "pf_45_degree_trendline",
    "pf_early_fulcrum_entry",
    "pf_trend_aligned_signal",
    "pf_vertical_count_target",
    "pf_horizontal_count_target",
    "pf_shakeout_filter",
    "pf_trap_reversal",
    "pf_one_box_semicatapult",
    "pf_one_box_fulcrum",
    "damir_fib_confluence_reversal",
    "damir_confirmed_trend_change",
    "damir_value_rejection_sequence",
    "damir_value_location_guideline",
    "damir_value_health_warning",
    "grail_bracket_lifecycle",
    "grail_regime_failure_warning",
    "anderson_conditional_bracket",
    "gann_reverse_signal_day",
    "gann_higher_tops_bottoms",
    "gann_halfway_point",
    "gann_repeated_level_reversal",
    "gann_secondary_reaction",
    "gann_fourth_level_reversal",
    "dalton_day_structure",
    "dalton_failed_range_extension",
    "dalton_single_print_retest",
    "elliott_wave_three_extension",
    "elliott_diagonal_rules",
    "brooks_breakout_pullback_test",
    "brooks_barbwire_filter",
    "brooks_breakout_mode",
    "brooks_failed_breakout_reversal",
    "brooks_measured_move_projection",
    "brooks_shrinking_stairs",
    "brooks_micro_measuring_gap",
    "brooks_always_in_mode",
    "brooks_trader_equation",
    "brooks_two_reasons_entry",
    "brooks_timeframe_discipline",
    "elder_triple_screen",
    "elder_impulse_censorship",
    "elder_force_index_pullback",
    "bulkowski_double_bottom",
    "bulkowski_double_top",
    "bulkowski_flag_breakout",
    "bulkowski_ascending_triangle",
    "bulkowski_falling_wedge",
    "bulkowski_broadening_bottom",
    "bulkowski_broadening_top",
    "bulkowski_right_angled_ascending",
    "bulkowski_right_angled_descending",
    "bulkowski_ascending_broadening_wedge",
    "bulkowski_descending_broadening_wedge",
    "bulkowski_barr_bottom",
    "bulkowski_barr_top",
    "bulkowski_cup_with_handle",
    "bulkowski_inverted_cup_with_handle",
    "bulkowski_diamond_bottom",
    "bulkowski_diamond_top",
    "bulkowski_high_tight_flag",
    "bulkowski_gap",
    "bulkowski_head_shoulders_bottom",
    "bulkowski_complex_head_shoulders_bottom",
    "bulkowski_head_shoulders_top",
    "bulkowski_complex_head_shoulders_top",
    "bulkowski_horn_bottom",
    "bulkowski_horn_top",
    "bulkowski_island_reversal",
    "bulkowski_long_island",
    "bulkowski_measured_move_down",
    "bulkowski_measured_move_up",
    "bulkowski_pennant",
    "bulkowski_pipe_bottom",
    "bulkowski_pipe_top",
    "bulkowski_rectangle_bottom",
    "bulkowski_rectangle_top",
    "bulkowski_rounding_bottom",
    "bulkowski_rounding_top",
    "bulkowski_ascending_scallop",
    "bulkowski_ascending_inverted_scallop",
    "bulkowski_descending_scallop",
    "bulkowski_descending_inverted_scallop",
    "bulkowski_descending_triangle",
    "bulkowski_symmetrical_triangle",
    "bulkowski_rising_wedge",
    "bulkowski_triple_bottom",
    "bulkowski_triple_top",
    "bulkowski_three_falling_peaks",
    "bulkowski_three_rising_valleys",
    "bulkowski_dead_cat_bounce",
    "bulkowski_inverted_dead_cat_bounce",
    "bulkowski_earnings_surprise_good",
    "bulkowski_earnings_surprise_bad",
    "bulkowski_fda_drug_approval",
    "bulkowski_earnings_flag",
    "bulkowski_same_store_sales_good",
    "bulkowski_same_store_sales_bad",
    "bulkowski_stock_downgrade",
    "bulkowski_stock_upgrade",
    "carter_scalper_alert",
    "carter_tick_extreme_fade",
    "carter_anchor_squeeze",
    "carter_brick_reversal",
    "carter_holp_lohp",
    "carter_end_of_day_fade",
    "carter_ema_propulsion",
    "carter_opening_gap_fade",
    "carter_pivot_play",
    "carter_atr_mean_reversion",
    "carter_tick_flow_follow",
    "carter_352_play",
    "schwager_bull_bear_trap",
    "schwager_false_trend_breakout",
    "schwager_filled_gap_failure",
    "schwager_spike_extreme_failure",
    "schwager_wide_range_day_failure",
    "schwager_counter_flag_failure",
    "aziz_bottom_reversal",
    "aziz_top_reversal",
    "aziz_moving_average_trend",
    "aziz_vwap_control",
    "aziz_stock_in_play_scanner",
    "aziz_premarket_gapper_scanner",
    "aziz_relative_volume_independence",
    "aziz_reversal_market_context",
    "aziz_opening_range_breakout",
    "grimes_pullback_quality",
    "grimes_three_push_exhaustion",
    "developing_hft_flow_exhaustion",
    "developing_hft_liquidity_depth",
    "developing_hft_volatility_clustering",
    "developing_hft_stat_arb_dislocation",
    "developing_hft_news_impact",
    "harris_immediacy_cost",
    "harris_limit_order_regret",
    "harris_stop_order_momentum",
    "murphy_inverse_relationship",
    "murphy_lead_lag_confirmation",
    "murphy_relationship_regime",
    "murphy_sector_rotation",
    "schwager_ma_turn_filter",
    "schwager_range_breakout_confirmation",
    "schwager_range_participation_filter",
    "schwager_restrictive_reversal_day",
    "schwager_minor_reaction_reentry",
    "schwager_long_ma_reaction",
    "schwager_oscillator_price_confirmation",
    "schwager_trend_adjusted_oscillator",
    "schwager_island_reversal_validation",
    "schwager_equity_deterioration_warning",
    "schwager_record_extreme_continuation",
    "schwager_narrow_consolidation_bias",
    "schwager_news_non_followthrough_reversal",
    "oreste_qpl_interaction",
    "oreste_entelechy_confluence",
    "oreste_time_price_confluence",
    "oreste_volatility_scaled_risk",
    "cartea_regime_rebate_safety",
    "cartea_inventory_skew",
    "cartea_state_intensity",
    "cartea_quote_freshness_guard",
    "aldridge_pair_dislocation",
    "dalton_trend_day_integrity",
    "dalton_auction_point_retest",
    "process_discipline_control",
    "douglas_probability_edge",
    "tendler_process_error",
    "drakoln_plan_integrity",
    "narang_horizon_specification",
    "narang_conditional_alpha",
    "narang_linear_alpha_blend",
    "narang_alpha_rotation",
    "narang_run_frequency_tradeoff",
    "davey_euro_night_strategy",
    "davey_euro_day_strategy",
    "davey_three_bar_baseline",
    "narang_cost_hurdle",
    "narang_liquidity_impact",
    "narang_forecast_bucket_monotonicity",
    "narang_time_decay",
    "narang_parameter_robustness",
    "narang_portfolio_value_add",
    "narang_risk_monitoring",
    "narang_regime_change_warning",
    "narang_exogenous_shock_filter",
    "narang_contagion_exposure",
    "brown_ma_stack_filter",
    "brown_band_signal_filter",
    "brown_structural_stop_buffer",
    "brown_qmp_filter_trigger",
    "brown_macd_zero_filter",
    "brown_qqe_filter",
    "brown_multi_ma_alignment",
    "brown_trendline_break_reentry",
    "brown_divergence_type_filter",
    "brown_bollinger_trade_management",
    "pyramiding_risk_lock",
    "grinold_information_horizon",
    "grinold_trade_utility",
    "grinold_fundamental_law",
    "grinold_alpha_scaling",
    "grinold_turnover_frontier",
    "pole_spread_reversion",
    "pole_popcorn_reversion",
    "pole_turning_point_event",
    "pole_event_pair_selection",
    "pole_staged_spread_entries",
    "pole_forecast_monitoring",
    "pole_cuscore_change_point",
    "pole_75_percent_reversion",
    "pole_multi_step_reversion",
    "pole_spread_margin",
    "pole_evolutionary_operation",
    "pole_catastrophe_entry",
    "pole_catastrophe_exit",
    "velu_omnibus_rule",
    "velu_fair_value_residual",
    "velu_sign_magnitude_decomposition",
    "velu_alexander_filter",
    "velu_sma_rule",
    "velu_ewa_rule",
    "velu_bwma_bollinger_rule",
    "velu_moving_average_oscillator",
    "velu_rsi_reversal",
    "velu_kernel_pattern",
    "velu_characteristic_time",
    "velu_intraday_profile",
    "velu_volume_return_filter",
    "velu_square_root_cost_hurdle",
    "velu_distance_pairs",
    "velu_microstructure_noise_sampling",
    "velu_duration_intensity",
    "gray_vogel_path_momentum",
    "gray_vogel_rebalance_tradeoff",
    "gray_vogel_lookback_regime",
    "gray_vogel_lottery_avoidance",
    "gray_vogel_seasonality_timing",
    "gray_vogel_52_week_high",
    "gray_vogel_absolute_strength",
    "gray_vogel_momentum_stop_loss",
    "gray_vogel_time_series_overlay",
    "gray_vogel_fundamental_momentum",
    "lien_intraday_range_reversal",
    "lien_medium_term_breakout",
    "lien_double_zero_fade",
    "lien_wait_for_real_deal",
    "lien_fader",
    "lien_filter_false_breakout",
    "lien_channel_breakout",
    "lien_perfect_order",
    "lien_short_term_momentum_20_100",
    "lien_proactive_news",
    "lien_reactive_news",
    "lien_combined_news",
    "lien_high_probability_turn",
    "lien_two_day_low_stop",
    "lien_two_stage_profit_management",
    "link_ten_period_breakout",
    "link_trendline_buffer_breakout",
    "link_opening_range_breakout_30m",
    "link_reversal_day",
    "link_double_top_bottom_reversal",
    "link_pain_reversal",
    "link_key_number_reversal",
    "link_multi_timeframe_confirmation",
    "link_news_reaction_fade",
    "link_stochastic_wave_entry",
    "link_stochastic_cross_entry",
    "link_stochastic_extreme_retest",
    "link_rsi_fifty_line_entry",
    "link_rsi_extreme_exit",
    "link_rsi_pattern_break",
    "link_macd_signal_line_entry",
    "link_adx_regime_switch",
    "link_stochastic_failed_move",
    "link_trend_retracement_entry",
    "link_atr_risk_feasibility",
    "link_stop_discipline",
    "momentum",
    "market_profile",
    "mean_reversion",
    "trend_structure",
    "breakout_quality",
    "pullback_retest",
    "price_action_candles",
    "momentum_exhaustion",
    "volume_price",
    "volume_open_interest",
    "murphy_percentage_retracement",
    "murphy_speed_resistance_lines",
    "volatility_regime",
    "microstructure",
    "mean_reversion_vs_momentum",
    "higher_timeframe_alignment",
    "session_liquidity",
    "risk_reward_geometry",
    "validation_integrity",
    "market_profile_auction",
    "statistical_arbitrage",
    "oscillator_signal",
    "scalping_execution",
    "support_resistance",
    "chart_patterns",
    "moving_average_context",
    "channel_analysis",
    "range_edge_rejection",
    "volatility_breakout",
    "divergence",
    "opening_range",
    "news_event_risk",
    "liquidity_sweep",
    "correlation_context",
    "trade_management",
    "bollinger_bands",
    "macd_signal",
    "atr_regime",
    "fibonacci_retracement",
    "pivot_levels",
    "rsi_reversal",
    "stochastic_reversal",
    "donchian_breakout",
    "adx_trend_strength",
    "keltner_channel",
    "ichimoku_context",
    "cci_reversal",
    "williams_reversal",
    "vwap_context",
    "obv_volume",
    "rate_of_change",
    "parabolic_sar",
    "elliott_wave",
    "harmonic_patterns",
    "gann_levels",
    "cointegration_pairs",
    "kalman_filter",
    "seasonality_context",
    "order_book_imbalance",
    "volume_profile_context",
    "fundamental_macro",
    "sentiment_positioning",
    "time_series_forecasting",
    "machine_learning_signal",
    "portfolio_allocation",
    "bollinger_pair_mean_reversion",
    "ten_period_sd_breakout",
    "triple_screen",
    "volume_spread_analysis",
    "candlestick_patterns",
    "initial_balance_profile",
    "cross_sectional_momentum",
    "meta_labeling",
    "force_index",
    "elder_impulse",
    "market_making_inventory",
    "forecast_combination",
    "triple_barrier_label",
    "purged_walk_forward",
    "deprado_sample_uniqueness",
    "deprado_sequential_bootstrap",
    "deprado_combinatorial_purged_cv",
    "deprado_probabilistic_sharpe",
    "deprado_deflated_sharpe",
    "deprado_strategy_failure_probability",
    "deprado_cusum_filter",
    "deprado_entropy",
    "deprado_tick_imbalance_bar",
    "deprado_volume_imbalance_bar",
    "deprado_dollar_imbalance_bar",
    "deprado_tick_runs_bar",
    "deprado_volume_runs_bar",
    "deprado_dollar_runs_bar",
    "deprado_tick_bar",
    "deprado_volume_bar",
    "deprado_dollar_bar",
    "realized_volatility",
    "fractional_differentiation",
    "risk_parity_allocation",
    "vwap_execution",
    "twap_execution",
    "participation_execution",
    "ewmac_trend_following",
    "carry_rule",
    "ab_system",
    "carver_forecast_cap",
    "carver_position_inertia",
    "carver_speed_limit",
    "carter_multisetup_confirmation",
    "chan_exit_policy",
    "elder_safezone_stop",
    "carter_tick_price_divergence",
    "carter_tick_noise_regime",
    "wyckoff_spring_upthrust",
    "ttm_squeeze",
    "al_brooks_second_entry",
    "kangaroo_tail",
    "relative_strength",
    "point_and_figure",
    "cycle_analysis",
    "factor_momentum",
    "fundamental_law",
    "market_impact",
    "garch_volatility",
    "hawkes_order_flow",
    "turtle_breakout",
    "volatility_targeting",
    "position_sizing",
    "random_forest_signal",
    "bayesian_pairs",
    "pca_eigenportfolio",
    "bet_sizing",
    "feature_importance_stability",
    "stochastic_volatility",
    "quantum_finance_scenario_stress",
)

REQUIRED_RESULT_FIELDS = frozenset({
    "algorithm_id",
    "applicability",
    "view",
    "reasons",
    "inputs_used",
    "missing_inputs",
    "source_books",
    "execution_authority",
    "uses_future_data",
    "research_only",
})


def _failed_result(name: str, reason: str, *, source_books: Sequence[str] = ()) -> dict[str, Any]:
    """Return a conservative result when a research evaluator is unusable."""
    return {
        "algorithm_id": name,
        "view": "MISSING_DATA",
        "candidate_side": None,
        "applicability": "MISSING_DATA",
        "reasons": [reason],
        "warnings": ["evaluator_failed_closed"],
        "missing_inputs": ["algorithm_evaluation"],
        "inputs_used": [],
        "source_books": list(source_books),
        "execution_authority": False,
        "uses_future_data": False,
        "research_only": True,
        "no_lookahead": True,
    }


def _validated_result(name: str, result: Any, *, source_books: Sequence[str] = ()) -> dict[str, Any]:
    if not isinstance(result, Mapping):
        return _failed_result(name, "invalid_result:not_a_mapping", source_books=source_books)

    item = dict(result)
    missing = sorted(REQUIRED_RESULT_FIELDS - set(item))
    if missing:
        return _failed_result(
            name,
            "invalid_result:missing_fields=" + ",".join(missing),
            source_books=source_books,
        )
    if item.get("algorithm_id") != name:
        return _failed_result(name, "invalid_result:algorithm_id_mismatch", source_books=source_books)
    if item.get("execution_authority") is not False:
        return _failed_result(name, "invalid_result:execution_authority_not_false", source_books=source_books)
    if item.get("uses_future_data") is not False:
        return _failed_result(name, "invalid_result:future_data_declared", source_books=source_books)
    if item.get("research_only") is not True:
        return _failed_result(name, "invalid_result:not_research_only", source_books=source_books)
    for field in ("reasons", "inputs_used", "missing_inputs", "source_books"):
        if not isinstance(item.get(field), list):
            return _failed_result(name, f"invalid_result:{field}_not_list", source_books=source_books)
    return item


def evaluate_module(name: str, state: Mapping[str, Any]) -> dict[str, Any]:
    """Evaluate one read-only algorithm and contain module failures locally."""
    if name not in ALGORITHM_MODULES:
        raise ValueError(f"unknown Watcher algorithm: {name}")
    module_name = f"{__name__}.{name}"
    module = None
    try:
        module = import_module(module_name)
        result = module.evaluate(state)
        source_books = getattr(module, "SOURCES", ())
        return _validated_result(name, result, source_books=source_books)
    except Exception as exc:  # research perspective failures must not stop the Watcher
        source_books = getattr(module, "SOURCES", ()) if module is not None else ()
        return _failed_result(
            name,
            f"algorithm_evaluation_error:{type(exc).__name__}",
            source_books=source_books,
        )


@lru_cache(maxsize=32)
def _loaded_selected_algorithm_modules(
    names: tuple[str, ...], loader: Any = import_module
) -> tuple[tuple[str, Any, tuple[str, ...], str | None], ...]:
    """Resolve only an explicit bounded selection for high-volume replay."""
    loaded: list[tuple[str, Any, tuple[str, ...], str | None]] = []
    for name in names:
        try:
            module = loader(f"{__name__}.{name}")
            source_books = tuple(str(value) for value in getattr(module, "SOURCES", ()))
            loaded.append((name, module, source_books, None))
        except Exception as exc:
            loaded.append((name, None, (), f"algorithm_evaluation_error:{type(exc).__name__}"))
    return tuple(loaded)


def evaluate_selected(names: Sequence[str], state: Mapping[str, Any]) -> list[dict[str, Any]]:
    """Evaluate only a validated, bounded selection without per-row imports."""
    selected = tuple(str(name) for name in names)
    unknown = [name for name in selected if name not in ALGORITHM_MODULES]
    if unknown:
        raise ValueError("unknown Watcher algorithm: " + ",".join(unknown))
    evaluation_state = state if isinstance(state, CachedState) else CachedState(state)
    results: list[dict[str, Any]] = []
    for name, module, source_books, import_error in _loaded_selected_algorithm_modules(selected):
        if module is None:
            results.append(_failed_result(name, import_error or "algorithm_import_error", source_books=source_books))
            continue
        try:
            results.append(_validated_result(name, module.evaluate(evaluation_state), source_books=source_books))
        except Exception as exc:
            results.append(_failed_result(name, f"algorithm_evaluation_error:{type(exc).__name__}", source_books=source_books))
    return results


@lru_cache(maxsize=8)
def _loaded_algorithm_modules(loader: Any = import_module) -> tuple[tuple[str, Any, tuple[str, ...], str | None], ...]:
    """Resolve the complete registry once for high-volume historical replay."""
    loaded: list[tuple[str, Any, tuple[str, ...], str | None]] = []
    for name in ALGORITHM_MODULES:
        try:
            module = loader(f"{__name__}.{name}")
            source_books = tuple(str(value) for value in getattr(module, "SOURCES", ()))
            loaded.append((name, module, source_books, None))
        except Exception as exc:  # retain per-algorithm fail-closed behavior
            # Preserve the historic evaluator-facing failure reason even when
            # module resolution is cached for replay.
            loaded.append((name, None, (), f"algorithm_evaluation_error:{type(exc).__name__}"))
    return tuple(loaded)


def evaluate_all(state: Mapping[str, Any]) -> list[dict[str, Any]]:
    evaluation_state = state if isinstance(state, CachedState) else CachedState(state)
    results: list[dict[str, Any]] = []
    for name, module, source_books, import_error in _loaded_algorithm_modules(import_module):
        if module is None:
            results.append(_failed_result(name, import_error or "algorithm_import_error", source_books=source_books))
            continue
        try:
            result = module.evaluate(evaluation_state)
            results.append(_validated_result(name, result, source_books=source_books))
        except Exception as exc:  # research perspective failures stay local
            results.append(
                _failed_result(
                    name,
                    f"algorithm_evaluation_error:{type(exc).__name__}",
                    source_books=source_books,
                )
            )
    return results


__all__ = ["ALGORITHM_MODULES", "REQUIRED_RESULT_FIELDS", "evaluate_all", "evaluate_module", "evaluate_selected"]
