with open(r'C:/Users/Zaid barghouthi/Desktop/trading_bot/bot/aegis/research_factory/core.py', 'r') as f:
    content = f.read()

idx = content.find('def main():')
if idx >= 0:
    new_method = '''\n    def _calculate_trade_metrics(self, trades: List[Dict[str, Any]]) -> Dict[str, Any]:\n        """Calculate real trade metrics from actual trades."""\n        if not trades:\n            return {}\n        \n        pnls = [t["pnl_pct"] for t in trades]\n        wins = [p for p in pnls if p > 0]\n        losses = [p for p in pnls if p <= 0]\n        \n        win_rate = len(wins) / len(pnls) if pnls else 0\n        loss_rate = 1 - win_rate\n        avg_win = np.mean(wins) if wins else 0\n        avg_loss = np.mean(losses) if losses else 0\n        expectancy = (win_rate * avg_win) + (loss_rate * avg_loss)\n        \n        gross_profit = sum(wins) if wins else 0\n        gross_loss = abs(sum(losses)) if losses else 0\n        profit_factor = gross_profit / gross_loss if gross_loss > 0 else float('inf')\n        \n        pnls_sorted = sorted(pnls)\n        p95_idx = int(len(pnls_sorted) * 0.05)\n        p99_idx = int(len(pnls_sorted) * 0.01)\n        p95_loss = pnls_sorted[p95_idx] if pnls_sorted else 0\n        p99_loss = pnls_sorted[p99_idx] if pnls_sorted else 0\n        max_loss = min(pnls) if pnls else 0\n        \n        # Calculate drawdown\n        equity_curve = np.cumsum(pnls)\n        running_max = np.maximum.accumulate(equity_curve)\n        drawdown = (running_max - equity_curve) / np.where(running_max != 0, running_max, 1)\n        max_drawdown = drawdown.max() if len(drawdown) > 0 else 0\n        \n        wins_erased_by_avg_loss = abs(avg_loss) / avg_win if avg_win != 0 else 0\n        wins_erased_by_tail_loss = abs(p95_loss) / avg_win if avg_win != 0 else 0\n        \n        return {\n            "win_rate": win_rate,\n            "loss_rate": 1 - win_rate,\n            "expectancy": expectancy,\n            "profit_factor": profit_factor if profit_factor != float('inf') else 999,\n            "avg_win": avg_win,\n            "avg_loss": avg_loss,\n            "p95_loss": p95_loss,\n            "p99_loss": p99_loss,\n            "max_loss": max_loss,\n            "max_drawdown": max_drawdown,\n            "wins_erased_by_avg_loss": abs(avg_loss) / avg_win if avg_win != 0 else 0,\n            "wins_erased_by_tail_loss": abs(p95_loss) / avg_win if avg_win != 0 else 0,\n            "total_trades": len(trades),\n            "net_pnl": sum(pnls),\n        }\n\n'''

    content = content[:idx] + new_method + content[idx:]
    with open(r'C:/Users/Zaid barghouthi/Desktop/trading_bot/bot/aegis/research_factory/core.py', 'w') as f:
        f.write(content)
    print('Added _calculate_trade_metrics method')